{% set version = "1.4.6.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shape
  version: {{ version|replace("-", "_") }}

source:
  fn: shape_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/shape_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/shape/shape_{{ version }}.tar.gz
  sha256: 43f9bd0f997fd6cf1838efd8b2509c9a6396513f4e54a20360481634affd22a4

build:
  noarch: generic
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('shape')"  # [not win]
    - "\"%R%\" -e \"library('shape')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=shape
  license: GPL (>= 3)
  summary: Functions for plotting graphical shapes such as ellipses, circles, cylinders, arrows,
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
