{% set version = "1.4.5" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shape
  version: {{ version|replace("-", "_") }}

source:
  fn: shape_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/shape_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/shape/shape_{{ version }}.tar.gz
  sha256: 094a79b8f42226189227fd7af71868e42106caa25a4d7f80a26977e8bc84189f

build:
  noarch: generic
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('shape')"  # [not win]
    - "\"%R%\" -e \"library('shape')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=shape
  license: GPL (>= 3)
  summary: Functions for plotting graphical shapes such as ellipses, circles, cylinders, arrows,
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
