travis:
  secure:
    BINSTAR_TOKEN: IvSpQW4tjIK2d2Dl2Juig4oSzC1Hfyqf7YUbKH47qk8/VogFpp61nO020kECcHMAwvA9oi/2aS3ut48L5Y0h40KWQp0xvIvlaCj3p0PUuEglOffkauu8vRBjGqPs84416UowDwUo7r956/WJPXH/14/EqTey8a+Kw3X4Z0piBeoZ5DRdc6akel8lpm3/3esmR/AsQQ3AiLFtsDf5YQkfuzudLLnz6OoNbdx1bTWvn4KD6t0KasLNvd0omRWQt0akwrdRomuls19LuHs62lCxBANwoPi8/Moa2azGSs08h3/CGQcX3skX12Jb/2BAu6azEzlW4eM1DfccnlMEPTeUc9KR6sz0z/AGoP7Y4Z7qr6zckQ5Yu8IHHLZcELWHm5I9FfQkHQj6p+Y0KAe2RAYlb9sheFWz2+WdIJknMK4Rn4Fkm/p00saDb0T+i6+yw6MScqIYYVVD45TcHM+ilef4HmXpFMkYkENx39TXA5NAhjp+m5YRWFg6sIEJB8FJuhy2l+8qNkDWdjo87YSI9CGEZM1PiwIt8VxF855f4ene9DwvMcBRzxcJyZM0gABc42m3CYxA8ud2bh8OOPTbfOuer0Y5PYGnuQauc7dBhyIlV98QKIUAqqDEsiRW16jqffsL5LVy9GrdEtYmPNrg/2PZGxfw+Bhnei7lDgBWX6Dhipc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
